// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class BudgetServiceLogging: BudgetServiceStub {
    let inner: any BudgetServiceStub
    let logger: Logger

    public init(_ inner: any BudgetServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudBillingBudgetsV1"
      logger[metadataKey: "gcp.client.service"] = "billingbudgets"
      logger[metadataKey: "gcp.experimental.swift.client"] = "BudgetService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createBudget(
      request: CreateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        name: "createBudget",
        action: {
          (r: CreateBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.createBudget(request: r, options: o)
        })
    }

    public func updateBudget(
      request: UpdateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateBudget",
        action: {
          (r: UpdateBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.updateBudget(request: r, options: o)
        })
    }

    public func getBudget(
      request: GetBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        name: "getBudget",
        action: {
          (r: GetBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.getBudget(request: r, options: o)
        })
    }

    public func listBudgets(
      request: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listBudgets",
        action: {
          (r: ListBudgetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse
          in
          return try await self.inner.listBudgets(request: r, options: o)
        })
    }

    public func deleteBudget(
      request: DeleteBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteBudget",
        action: { (r: DeleteBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBudget(request: r, options: o)
        })
    }
  }
}
