// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// BudgetService stores Cloud Billing budgets, which define a
/// budget plan and rules to execute as we track spend against that plan.
///
/// @Snippet(path: "BudgetServiceQuickstart")
public final class BudgetServiceClient: Clients.BudgetServiceProtocol, Sendable {
  let inner: any Clients.BudgetServiceStub

  /// Creates a new `BudgetServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.BudgetServiceStub = try Clients.BudgetServiceTransport(options)
    inner = Clients.BudgetServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.BudgetServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new budget. See
  /// [Quotas and limits](https://cloud.google.com/billing/quotas)
  /// for more information on the limits of the number of budgets you can create.
  ///
  /// @Snippet(path: "BudgetService_CreateBudget")
  public func createBudget(
    request: CreateBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    try await self.inner.createBudget(request: request, options: options)
  }

  /// Updates a budget and returns the updated budget.
  ///
  /// WARNING: There are some fields exposed on the Google Cloud Console that
  /// aren't available on this API. Budget fields that are not exposed in
  /// this API will not be changed by this method.
  ///
  /// @Snippet(path: "BudgetService_UpdateBudget")
  public func updateBudget(
    request: UpdateBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    try await self.inner.updateBudget(request: request, options: options)
  }

  /// Returns a budget.
  ///
  /// WARNING: There are some fields exposed on the Google Cloud Console that
  /// aren't available on this API. When reading from the API, you will not
  /// see these fields in the return value, though they may have been set
  /// in the Cloud Console.
  ///
  /// @Snippet(path: "BudgetService_GetBudget")
  public func getBudget(
    request: GetBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    try await self.inner.getBudget(request: request, options: options)
  }

  /// Returns a list of budgets for a billing account.
  ///
  /// WARNING: There are some fields exposed on the Google Cloud Console that
  /// aren't available on this API. When reading from the API, you will not
  /// see these fields in the return value, though they may have been set
  /// in the Cloud Console.
  ///
  /// @Snippet(path: "BudgetService_ListBudgets")
  public func listBudgets(
    request: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse {
    try await self.inner.listBudgets(request: request, options: options)
  }

  /// Returns a list of budgets for a billing account.
  ///
  /// WARNING: There are some fields exposed on the Google Cloud Console that
  /// aren't available on this API. When reading from the API, you will not
  /// see these fields in the return value, though they may have been set
  /// in the Cloud Console.
  ///
  /// @Snippet(path: "BudgetService_ListBudgets")
  public func listBudgets(
    byItem: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Budget, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listBudgets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Deletes a budget. Returns successfully if already deleted.
  ///
  /// @Snippet(path: "BudgetService_DeleteBudget")
  public func deleteBudget(
    request: DeleteBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteBudget(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `BudgetServiceClient`.
  ///
  /// To mock `BudgetServiceClient` change your functions to receive
  /// `some BudgetServiceProtocol` or `any BudgetServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol BudgetServiceProtocol {
    /// See `BudgetServiceClient.createBudget`.
    func createBudget(request: CreateBudgetRequest) async throws
      -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.createBudget`.
    func createBudget(
      parent: Swift.String,
      budget: Budget?,
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.updateBudget`.
    func updateBudget(request: UpdateBudgetRequest) async throws
      -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.updateBudget`.
    func updateBudget(
      budget: Budget?,
      updateMask: GoogleCloudWKT.FieldMask?,
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.getBudget`.
    func getBudget(request: GetBudgetRequest) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.getBudget`.
    func getBudget(
      name: Swift.String,
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.listBudgets`.
    func listBudgets(request: ListBudgetsRequest) async throws
      -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse

    /// See `BudgetServiceClient.listBudgets`.
    func listBudgets(
      byItem: ListBudgetsRequest
    ) throws -> any AsyncSequence<Budget, Swift.Error>

    /// See `BudgetServiceClient.listBudgets`.
    func listBudgets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Budget, Swift.Error>

    /// See `BudgetServiceClient.deleteBudget`.
    func deleteBudget(request: DeleteBudgetRequest) async throws

    /// See `BudgetServiceClient.deleteBudget`.
    func deleteBudget(
      name: Swift.String,
    ) async throws

    /// See `BudgetServiceClient.createBudget`.
    func createBudget(
      request: CreateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.updateBudget`.
    func updateBudget(
      request: UpdateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.getBudget`.
    func getBudget(
      request: GetBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget

    /// See `BudgetServiceClient.listBudgets`.
    func listBudgets(
      request: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse

    /// See `BudgetServiceClient.listBudgets`.
    func listBudgets(
      byItem: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Budget, Swift.Error>

    /// See `BudgetServiceClient.deleteBudget`.
    func deleteBudget(
      request: DeleteBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.BudgetServiceProtocol {
  public func createBudget(request: CreateBudgetRequest) async throws
    -> GoogleCloudBillingBudgetsV1.Budget
  {
    try await self.createBudget(request: request, options: .init())
  }

  public func createBudget(
    request: CreateBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createBudget(
    parent: Swift.String,
    budget: Budget?,
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    let request = CreateBudgetRequest().with {
      $0.parent = parent
      $0.budget = budget
    }
    return try await self.createBudget(request: request)
  }

  public func updateBudget(request: UpdateBudgetRequest) async throws
    -> GoogleCloudBillingBudgetsV1.Budget
  {
    try await self.updateBudget(request: request, options: .init())
  }

  public func updateBudget(
    request: UpdateBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateBudget(
    budget: Budget?,
    updateMask: GoogleCloudWKT.FieldMask?,
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    let request = UpdateBudgetRequest().with {
      $0.budget = budget
      $0.updateMask = updateMask
    }
    return try await self.updateBudget(request: request)
  }

  public func getBudget(request: GetBudgetRequest) async throws
    -> GoogleCloudBillingBudgetsV1.Budget
  {
    try await self.getBudget(request: request, options: .init())
  }

  public func getBudget(
    request: GetBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getBudget(
    name: Swift.String,
  ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
    let request = GetBudgetRequest().with {
      $0.name = name
    }
    return try await self.getBudget(request: request)
  }

  public func listBudgets(request: ListBudgetsRequest) async throws
    -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse
  {
    try await self.listBudgets(request: request, options: .init())
  }

  public func listBudgets(
    request: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listBudgets(
    byItem: ListBudgetsRequest
  ) throws -> any AsyncSequence<Budget, Swift.Error> {
    try self.listBudgets(byItem: byItem, options: .init())
  }

  public func listBudgets(
    byItem: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Budget, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listBudgets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Budget, Swift.Error> {
    let request = ListBudgetsRequest().with {
      $0.parent = parent
    }
    return try self.listBudgets(byItem: request)
  }

  public func deleteBudget(request: DeleteBudgetRequest) async throws {
    try await self.deleteBudget(request: request, options: .init())
  }

  public func deleteBudget(
    request: DeleteBudgetRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteBudget(
    name: Swift.String,
  ) async throws {
    let request = DeleteBudgetRequest().with {
      $0.name = name
    }
    try await self.deleteBudget(request: request)
  }
}
