// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class BudgetServiceRetry: BudgetServiceStub {
    let inner: any BudgetServiceStub
    let options: GoogleCloudGax.ClientOptions

    public init(_ inner: any BudgetServiceStub, options: GoogleCloudGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleCloudGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createBudget(
      request: CreateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.createBudget(request: r, options: o)
        })
    }

    public func updateBudget(
      request: UpdateBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.updateBudget(request: r, options: o)
        })
    }

    public func getBudget(
      request: GetBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.Budget {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.Budget
          in
          return try await self.inner.getBudget(request: r, options: o)
        })
    }

    public func listBudgets(
      request: ListBudgetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListBudgetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudBillingBudgetsV1.ListBudgetsResponse
          in
          return try await self.inner.listBudgets(request: r, options: o)
        })
    }

    public func deleteBudget(
      request: DeleteBudgetRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteBudgetRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteBudget(request: r, options: o)
        })
    }
  }
}
