// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A budget is a plan that describes what you expect to spend on Cloud
/// projects, plus the rules to execute as spend is tracked against that plan,
/// (for example, send an alert when 90% of the target spend is met).
/// The budget time period is configurable, with options such as month (default),
/// quarter, year, or custom time period.
public struct Budget: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the budget.
  /// The resource name implies the scope of a budget. Values are of the form
  /// `billingAccounts/{billingAccountId}/budgets/{budgetId}`.
  public var name: Swift.String = Swift.String()

  /// User data for display name in UI. The name must be less than or equal to 60
  /// characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. Filters that define which resources are used to compute the
  /// actual spend against the budget amount, such as projects, services, and the
  /// budget's time period, as well as other filters.
  public var budgetFilter: Filter? = nil

  /// Required. Budgeted amount.
  public var amount: BudgetAmount? = nil

  /// Optional. Rules that trigger alerts (notifications of thresholds
  /// being crossed) when spend exceeds the specified percentages of the budget.
  ///
  /// Optional for `pubsubTopic` notifications.
  ///
  /// Required if using email notifications.
  public var thresholdRules: [ThresholdRule] = []

  /// Optional. Rules to apply to notifications sent based on budget spend and
  /// thresholds.
  public var notificationsRule: NotificationsRule? = nil

  /// Optional. Etag to validate that the object is unchanged for a
  /// read-modify-write operation.
  /// An empty etag causes an update to overwrite other changes.
  public var etag: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `Budget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Budget().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let budgetFilter = CodingKeys(stringValue: "budgetFilter")
    static let amount = CodingKeys(stringValue: "amount")
    static let thresholdRules = CodingKeys(stringValue: "thresholdRules")
    static let notificationsRule = CodingKeys(stringValue: "notificationsRule")
    static let etag = CodingKeys(stringValue: "etag")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "displayName",
      "budgetFilter",
      "amount",
      "thresholdRules",
      "notificationsRule",
      "etag",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    self.budgetFilter = try container.decodeIfPresent(Filter.self, forKey: .budgetFilter)
    self.amount = try container.decodeIfPresent(BudgetAmount.self, forKey: .amount)
    if let value = try container.decodeIfPresent([ThresholdRule].self, forKey: .thresholdRules) {
      self.thresholdRules = value
    }
    self.notificationsRule = try container.decodeIfPresent(
      NotificationsRule.self, forKey: .notificationsRule)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encodeIfPresent(self.budgetFilter, forKey: .budgetFilter)
    try container.encodeIfPresent(self.amount, forKey: .amount)
    try container.encode(self.thresholdRules, forKey: .thresholdRules)
    try container.encodeIfPresent(self.notificationsRule, forKey: .notificationsRule)
    try container.encode(self.etag, forKey: .etag)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.Budget"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
