// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// The budgeted amount for each usage period.
public struct BudgetAmount: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specification for what amount to use as the budget.
  public var budgetAmount: OneOf_BudgetAmount? = nil

  /// Initialize a new instance of `BudgetAmount`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BudgetAmount().with { $0.specifiedAmount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case specifiedAmount = "specifiedAmount"
    case lastPeriodAmount = "lastPeriodAmount"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var budgetAmount: OneOf_BudgetAmount? = nil
    let budgetAmountCheckAndSet = {
      if budgetAmount != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'budgetAmount'"))
      }
      budgetAmount = $0
    }
    if let specifiedAmount = try container.decodeIfPresent(
      GoogleType.Money?.self, forKey: .specifiedAmount)
    {
      try budgetAmountCheckAndSet(.specifiedAmount(specifiedAmount))
    }
    if let lastPeriodAmount = try container.decodeIfPresent(
      LastPeriodAmount?.self, forKey: .lastPeriodAmount)
    {
      try budgetAmountCheckAndSet(.lastPeriodAmount(lastPeriodAmount))
    }
    self.budgetAmount = budgetAmount
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.budgetAmount {
      switch choice {
      case .specifiedAmount(let value):
        try container.encode(value, forKey: .specifiedAmount)
      case .lastPeriodAmount(let value):
        try container.encode(value, forKey: .lastPeriodAmount)
      }
    }
  }

  /// Specification for what amount to use as the budget.
  public enum OneOf_BudgetAmount: Codable, Equatable, Sendable {
    /// A specified amount to use as the budget.
    /// `currency_code` is optional. If specified when creating a budget, it must
    /// match the currency of the billing account. If specified when updating a
    /// budget, it must match the currency_code of the existing budget.
    /// The `currency_code` is provided on output.
    indirect case specifiedAmount(GoogleType.Money?)
    /// Use the last period's actual spend as the budget for the present period.
    /// LastPeriodAmount can only be set when the budget's time period is a
    /// [Filter.calendar_period][google.cloud.billing.budgets.v1.Filter.calendar_period].
    /// It cannot be set in combination with
    /// [Filter.custom_period][google.cloud.billing.budgets.v1.Filter.custom_period].
    ///
    /// [google.cloud.billing.budgets.v1.Filter.calendar_period]: <doc:Filter/OneOf_UsagePeriod/calendarPeriod(_:)>
    /// [google.cloud.billing.budgets.v1.Filter.custom_period]: <doc:Filter/OneOf_UsagePeriod/customPeriod(_:)>
    indirect case lastPeriodAmount(LastPeriodAmount?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.BudgetAmount"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
