// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A filter for a budget, limiting the scope of the cost to calculate.
public struct Filter: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. A set of projects of the form `projects/{project}`,
  /// specifying that usage from only this set of projects should be
  /// included in the budget. If omitted, the report includes all usage for
  /// the billing account, regardless of which project the usage occurred on.
  public var projects: [Swift.String] = []

  /// Optional. A set of folder and organization names of the form
  /// `folders/{folderId}` or `organizations/{organizationId}`, specifying that
  /// usage from only this set of folders and organizations should be included in
  /// the budget. If omitted, the budget includes all usage that the billing
  /// account pays for. If the folder or organization contains projects that are
  /// paid for by a different Cloud Billing account, the budget *doesn't* apply
  /// to those projects.
  public var resourceAncestors: [Swift.String] = []

  /// Optional. If
  /// [Filter.credit_types_treatment][google.cloud.billing.budgets.v1.Filter.credit_types_treatment]
  /// is INCLUDE_SPECIFIED_CREDITS, this is a list of credit types to be
  /// subtracted from gross cost to determine the spend for threshold
  /// calculations. See [a list of acceptable credit type
  /// values](https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#credits-type).
  ///
  /// If
  /// [Filter.credit_types_treatment][google.cloud.billing.budgets.v1.Filter.credit_types_treatment]
  /// is **not** INCLUDE_SPECIFIED_CREDITS, this field must be empty.
  ///
  /// [google.cloud.billing.budgets.v1.Filter.credit_types_treatment]: <doc:Filter/creditTypesTreatment>
  public var creditTypes: [Swift.String] = []

  /// Optional. If not set, default behavior is `INCLUDE_ALL_CREDITS`.
  public var creditTypesTreatment: Filter.CreditTypesTreatment = Filter.CreditTypesTreatment()

  /// Optional. A set of services of the form `services/{service_id}`,
  /// specifying that usage from only this set of services should be
  /// included in the budget. If omitted, the report includes usage for
  /// all the services.
  /// The service names are available through the Catalog API:
  /// https://cloud.google.com/billing/v1/how-tos/catalog-api.
  public var services: [Swift.String] = []

  /// Optional. A set of subaccounts of the form `billingAccounts/{account_id}`,
  /// specifying that usage from only this set of subaccounts should be included
  /// in the budget. If a subaccount is set to the name of the parent account,
  /// usage from the parent account is included. If the field is omitted,
  /// the report includes usage from the parent account and all subaccounts,
  /// if they exist.
  public var subaccounts: [Swift.String] = []

  /// Optional. A single label and value pair specifying that usage from only
  /// this set of labeled resources should be included in the budget. If omitted,
  /// the report includes all labeled and unlabeled usage.
  ///
  /// An object containing a single `"key": value` pair. Example: `{ "name":
  /// "wrench" }`.
  ///
  ///  _Currently, multiple entries or multiple values per entry are not
  ///  allowed._
  public var labels: [Swift.String: GoogleWKT.ListValue] = [:]

  /// Multiple options to choose the budget's time period, specifying that only
  /// usage that occurs during this time period should be included in the budget.
  /// If not set, the <code>usage_period</code> defaults to CalendarPeriod.MONTH.
  public var usagePeriod: OneOf_UsagePeriod? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Filter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Filter().with { $0.projects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projects = CodingKeys(stringValue: "projects")
    static let resourceAncestors = CodingKeys(stringValue: "resourceAncestors")
    static let creditTypes = CodingKeys(stringValue: "creditTypes")
    static let creditTypesTreatment = CodingKeys(stringValue: "creditTypesTreatment")
    static let services = CodingKeys(stringValue: "services")
    static let subaccounts = CodingKeys(stringValue: "subaccounts")
    static let labels = CodingKeys(stringValue: "labels")
    static let calendarPeriod = CodingKeys(stringValue: "calendarPeriod")
    static let customPeriod = CodingKeys(stringValue: "customPeriod")

    static let _knownKeys: Set<Swift.String> = [
      "projects",
      "resourceAncestors",
      "creditTypes",
      "creditTypesTreatment",
      "services",
      "subaccounts",
      "labels",
      "calendarPeriod",
      "customPeriod",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .projects) {
      self.projects = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .resourceAncestors) {
      self.resourceAncestors = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .creditTypes) {
      self.creditTypes = value
    }
    if let value = try container.decodeIfPresent(
      Filter.CreditTypesTreatment.self, forKey: .creditTypesTreatment)
    {
      self.creditTypesTreatment = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .services) {
      self.services = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .subaccounts) {
      self.subaccounts = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: GoogleWKT.ListValue].self, forKey: .labels)
    {
      self.labels = value
    }

    var usagePeriod: OneOf_UsagePeriod? = nil
    let usagePeriodCheckAndSet = {
      if usagePeriod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'usagePeriod'"))
      }
      usagePeriod = $0
    }
    if let calendarPeriod = try container.decodeIfPresent(
      CalendarPeriod.self, forKey: .calendarPeriod)
    {
      try usagePeriodCheckAndSet(.calendarPeriod(calendarPeriod))
    }
    if let customPeriod = try container.decodeIfPresent(CustomPeriod?.self, forKey: .customPeriod) {
      try usagePeriodCheckAndSet(.customPeriod(customPeriod))
    }
    self.usagePeriod = usagePeriod
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projects, forKey: .projects)
    try container.encode(self.resourceAncestors, forKey: .resourceAncestors)
    try container.encode(self.creditTypes, forKey: .creditTypes)
    try container.encode(self.creditTypesTreatment, forKey: .creditTypesTreatment)
    try container.encode(self.services, forKey: .services)
    try container.encode(self.subaccounts, forKey: .subaccounts)
    try container.encode(self.labels, forKey: .labels)

    if let choice = self.usagePeriod {
      switch choice {
      case .calendarPeriod(let value):
        try container.encode(value, forKey: .calendarPeriod)
      case .customPeriod(let value):
        try container.encode(value, forKey: .customPeriod)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies how credits are applied when determining the spend for
  /// threshold calculations. Budgets track the total cost minus any applicable
  /// selected credits.
  /// [See the documentation for a list of credit
  /// types](https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#credits-type).
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum CreditTypesTreatment: Codable, Equatable, Sendable {
    case unspecified
    /// All types of credit are subtracted from the gross cost to determine the
    /// spend for threshold calculations.
    case includeAllCredits
    /// All types of credit are added to the net cost to determine the spend for
    /// threshold calculations.
    case excludeAllCredits
    /// [Credit
    /// types](https://cloud.google.com/billing/docs/how-to/export-data-bigquery-tables#credits-type)
    /// specified in the credit_types field are subtracted from the
    /// gross cost to determine the spend for threshold calculations.
    case includeSpecifiedCredits
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .includeAllCredits: return 1
      case .excludeAllCredits: return 2
      case .includeSpecifiedCredits: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CREDIT_TYPES_TREATMENT_UNSPECIFIED"
      case .includeAllCredits: return "INCLUDE_ALL_CREDITS"
      case .excludeAllCredits: return "EXCLUDE_ALL_CREDITS"
      case .includeSpecifiedCredits: return "INCLUDE_SPECIFIED_CREDITS"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CreditTypesTreatment/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CREDIT_TYPES_TREATMENT_UNSPECIFIED": self = .unspecified
      case "INCLUDE_ALL_CREDITS": self = .includeAllCredits
      case "EXCLUDE_ALL_CREDITS": self = .excludeAllCredits
      case "INCLUDE_SPECIFIED_CREDITS": self = .includeSpecifiedCredits
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CreditTypesTreatment/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .includeAllCredits
      case 2: self = .excludeAllCredits
      case 3: self = .includeSpecifiedCredits
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("CREDIT_TYPES_TREATMENT_UNSPECIFIED")
      case .includeAllCredits: return try container.encode("INCLUDE_ALL_CREDITS")
      case .excludeAllCredits: return try container.encode("EXCLUDE_ALL_CREDITS")
      case .includeSpecifiedCredits: return try container.encode("INCLUDE_SPECIFIED_CREDITS")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Multiple options to choose the budget's time period, specifying that only
  /// usage that occurs during this time period should be included in the budget.
  /// If not set, the <code>usage_period</code> defaults to CalendarPeriod.MONTH.
  public enum OneOf_UsagePeriod: Codable, Equatable, Sendable {
    /// Optional. Specifies to track usage for recurring calendar period.
    /// For example, assume that CalendarPeriod.QUARTER is set. The budget
    /// tracks usage from April 1 to June 30, when the current calendar month is
    /// April, May, June. After that, it tracks usage from July 1 to
    /// September 30 when the current calendar month is July, August, September,
    /// so on.
    case calendarPeriod(CalendarPeriod)
    /// Optional. Specifies to track usage from any start date (required) to any
    /// end date (optional). This time period is static, it does not recur.
    indirect case customPeriod(CustomPeriod?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.Filter"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
