// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request for ListBudgets
public struct ListBudgetsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Name of billing account to list budgets under. Values
  /// are of the form `billingAccounts/{billingAccountId}`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Set the scope of the budgets to be returned, in the format of the
  /// resource name. The scope of a budget is the cost that it tracks, such as
  /// costs for a single project, or the costs for all projects in a folder. Only
  /// project scope (in the format of "projects/project-id" or "projects/123") is
  /// supported in this field. When this field is set to a project's resource
  /// name, the budgets returned are tracking the costs for that project.
  public var scope: Swift.String = Swift.String()

  /// Optional. The maximum number of budgets to return per page.
  /// The default and maximum value are 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The value returned by the last `ListBudgetsResponse` which
  /// indicates that this is a continuation of a prior `ListBudgets` call,
  /// and that the system should return the next page of data.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListBudgetsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListBudgetsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.ListBudgetsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
