// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// NotificationsRule defines notifications that are sent based on budget spend
/// and thresholds.
public struct NotificationsRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. The name of the Pub/Sub topic where budget-related messages are
  /// published, in the form `projects/{project_id}/topics/{topic_id}`. Updates
  /// are sent to the topic at regular intervals; the timing of the updates is
  /// not dependent on the [threshold rules](#thresholdrule) you've set.
  ///
  /// Note that if you want your
  /// [Pub/Sub JSON
  /// object](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format)
  /// to contain data for `alertThresholdExceeded`, you need at least one
  /// [alert threshold rule](#thresholdrule). When you set threshold rules, you
  /// must also enable at least one of the email notification options, either
  /// using the default IAM recipients or Cloud Monitoring email notification
  /// channels.
  ///
  /// To use Pub/Sub topics with budgets, you must do the following:
  ///
  /// 1. Create the Pub/Sub topic
  /// before connecting it to your budget. For guidance, see
  /// [Manage programmatic budget alert
  /// notifications](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications).
  ///
  /// 2. Grant the API caller the `pubsub.topics.setIamPolicy` permission on
  /// the Pub/Sub topic. If not set, the API call fails with PERMISSION_DENIED.
  /// For additional details on Pub/Sub roles and permissions, see
  /// [Permissions required for this
  /// task](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#permissions_required_for_this_task).
  public var pubsubTopic: Swift.String = Swift.String()

  /// Optional. Required when
  /// [NotificationsRule.pubsub_topic][google.cloud.billing.budgets.v1.NotificationsRule.pubsub_topic]
  /// is set. The schema version of the notification sent to
  /// [NotificationsRule.pubsub_topic][google.cloud.billing.budgets.v1.NotificationsRule.pubsub_topic].
  /// Only "1.0" is accepted. It represents the JSON schema as defined in
  /// https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format.
  ///
  /// [google.cloud.billing.budgets.v1.NotificationsRule.pubsub_topic]: <doc:NotificationsRule/pubsubTopic>
  public var schemaVersion: Swift.String = Swift.String()

  /// Optional. Email targets to send notifications to when a threshold is
  /// exceeded. This is in addition to the `DefaultIamRecipients` who receive
  /// alert emails based on their billing account IAM role. The value is the full
  /// REST resource name of a Cloud Monitoring email notification channel with
  /// the form `projects/{project_id}/notificationChannels/{channel_id}`. A
  /// maximum of 5 email notifications are allowed.
  ///
  /// To customize budget alert email recipients with monitoring notification
  /// channels, you _must create the monitoring notification channels before
  /// you link them to a budget_. For guidance on setting up notification
  /// channels to use with budgets, see
  /// [Customize budget alert email
  /// recipients](https://cloud.google.com/billing/docs/how-to/budgets-notification-recipients).
  ///
  /// For Cloud Billing budget alerts, you _must use email notification
  /// channels_. The other types of notification channels are _not_
  /// supported, such as Slack, SMS, or PagerDuty. If you want to
  /// [send budget notifications to
  /// Slack](https://cloud.google.com/billing/docs/how-to/notify#send_notifications_to_slack),
  /// use a pubsubTopic and configure
  /// [programmatic
  /// notifications](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications).
  public var monitoringNotificationChannels: [Swift.String] = []

  /// Optional. When set to true, disables default notifications sent when a
  /// threshold is exceeded. Default notifications are sent to those with Billing
  /// Account Administrator and Billing Account User IAM roles for the target
  /// account.
  public var disableDefaultIamRecipients: Swift.Bool = Swift.Bool()

  /// Optional. When set to true, and when the budget has a single project
  /// configured, notifications will be sent to project level recipients of that
  /// project. This field will be ignored if the budget has multiple or no
  /// project configured.
  ///
  /// Currently, project level recipients are the users with `Owner` role on a
  /// cloud project.
  public var enableProjectLevelRecipients: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `NotificationsRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NotificationsRule().with { $0.pubsubTopic = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.NotificationsRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
