// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// ThresholdRule contains the definition of a threshold. Threshold rules define
/// the triggering events used to generate a budget notification email. When a
/// threshold is crossed (spend exceeds the specified percentages of the
/// budget), budget alert emails are sent to the email recipients you specify
/// in the
/// [NotificationsRule](#notificationsrule).
///
/// Threshold rules also affect the fields included in the
/// [JSON data
/// object](https://cloud.google.com/billing/docs/how-to/budgets-programmatic-notifications#notification_format)
/// sent to a Pub/Sub topic.
///
/// Threshold rules are _required_ if using email notifications.
///
/// Threshold rules are _optional_ if only setting a
/// [`pubsubTopic` NotificationsRule](#NotificationsRule),
/// unless you want your JSON data object to include data about the thresholds
/// you set.
///
/// For more information, see
/// [set budget threshold rules and
/// actions](https://cloud.google.com/billing/docs/how-to/budgets#budget-actions).
public struct ThresholdRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Send an alert when this threshold is exceeded.
  /// This is a 1.0-based percentage, so 0.5 = 50%.
  /// Validation: non-negative number.
  public var thresholdPercent: Swift.Double = Swift.Double()

  /// Optional. The type of basis used to determine if spend has passed the
  /// threshold. Behavior defaults to CURRENT_SPEND if not set.
  public var spendBasis: ThresholdRule.Basis = ThresholdRule.Basis()

  /// Initialize a new instance of `ThresholdRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ThresholdRule().with { $0.thresholdPercent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The type of basis used to determine if spend has passed the threshold.
  public enum Basis: Codable, Equatable, Sendable {
    /// Unspecified threshold basis.
    case unspecified
    /// Use current spend as the basis for comparison against the threshold.
    case currentSpend
    /// Use forecasted spend for the period as the basis for comparison against
    /// the threshold.
    /// FORECASTED_SPEND can only be set when the budget's time period is a
    /// [Filter.calendar_period][google.cloud.billing.budgets.v1.Filter.calendar_period].
    /// It cannot be set in combination with
    /// [Filter.custom_period][google.cloud.billing.budgets.v1.Filter.custom_period].
    ///
    /// [google.cloud.billing.budgets.v1.Filter.calendar_period]: <doc:Filter/calendarPeriod>
    /// [google.cloud.billing.budgets.v1.Filter.custom_period]: <doc:Filter/customPeriod>
    case forecastedSpend
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .currentSpend: return 1
      case .forecastedSpend: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BASIS_UNSPECIFIED"
      case .currentSpend: return "CURRENT_SPEND"
      case .forecastedSpend: return "FORECASTED_SPEND"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BASIS_UNSPECIFIED": self = .unspecified
      case "CURRENT_SPEND": self = .currentSpend
      case "FORECASTED_SPEND": self = .forecastedSpend
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .currentSpend
      case 2: self = .forecastedSpend
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .currentSpend: return try container.encode(1)
      case .forecastedSpend: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.billing.budgets.v1.ThresholdRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
